<?php
/* if ($this->pageCount): ?>
<div class="paginator">
 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    First
  </a> |
<?php else: ?>
  <span class="disabled">First</span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    < Previous
  </a> |
<?php else: ?>
  <span class="disabled">< Previous</span> |
<?php endif; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next >
  </a> |
<?php else: ?>
  <span class="disabled">Next ></span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    Last
  </a>
<?php else: ?>
  <span class="disabled">Last</span>
<?php endif; ?>
 
</div>
<?php endif;*/ ?>


<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <span>
    <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>


 de <?php echo $this->totalItemCount; ?>
 </span>
<!-- First page link -->
<?php if (isset($this->previous)): 
   ?>
  <a class="first" onclick="vesA(<?php echo $this->first; ?>)">
    Inici
  </a> |
<?php else:  ?>
  <span class="disabled">Inici</span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a class="prev" onclick="vesA(<?php echo $this->previous; ?>)" >
    &lt; Anterior
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Anterior</span> |
<?php endif; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a class="next" onclick="vesA(<?php echo $this->next; ?>)" >
    Seguent &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Seguent &gt;</span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a class="last" onclick="vesA(<?php echo $this->last; ?>)" >
    Últim
  </a>
<?php else: ?>
  <span class="disabled">Últim</span>
<?php endif; ?>
 
</div>
<?php endif; ?>